### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by PacoRabanne** [saschadiercks/personalNews#9]
Hi, me very interesting you project, but how add rss lent in config and where?
My telegram @ PacoRaco

**Comment by saschadiercks** [comment]
Hi Paco,
sorry for the very late reply. You can add feeds in this file: https://github.com/saschadiercks/personalNews/blob/master/htdocs/data/data.json
That's the file /htdocs/data/data.json after cloning the project.

The file has Groups ("Nachrichten","Tech News"...) which can be renamed.
In this groups you can add feed-sources and icons (icon is optional) as JSON-Objects.

This project probably needs a better instruction, do make this option easier to understand.
